config/routes.rb
Rails.application.routes.draw do
  get 'room/show'
  get 'room/create'
  get 'chats/create'
    devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  
  get 'search/search'
  root 'homes#top'
  get 'home/about' => "homes#about"
  

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :followers, on: :member
    get :followeds, on: :member
  end
  
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create, :destroy]
  end 
  
  resources :rooms, only: [:create, :show]
  resources :chats, only: [:create]
  
  resource :search, only: [:search]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_many :active_relationships, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy
  has_many :followeds, through: :active_relationships, source: :follower
  
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :followed
  
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  
  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}
  validates :postal_code, presence: true
  validates :prefecture_code, presence: true
  validates :city, presence: true
  validates :street, presence: true
  
  def followed_by?(user)
    passive_relationships.find_by(followed_id: user.id).present?
  end
  
  def favorited_by?(user)
	 favorites.where(user_id: user.id).exists?
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    ThanksMailer.with(user: @user).welcome_email.deliver_now
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end
  
  
  
  # def create
  #   super
  #   ContactMailer.send_signup_email(resource).deliver unless resource.invalid?
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :postal_code, :prefecture_code, :city, :street])
  end
  
  
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
                                                # def after_sign_up_path_for(resource)
                                                #   users_path
                                                # end
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :encrypted_password])
  end
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update,:edit]
  

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @room = Room.new
    @user_room = UserRoom.new
    @current_user_room = UserRoom.where(user_id: current_user.id)
    @your_user_room = UserRoom.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_user_room.each do |cu|
        @your_user_room.each do |u|
          if cu.room_id == u.room_id
            @our_room = true
            @room_id = cu.room_id
          else
            @room = Room.new
            @user_room = UserRoom.new
          end
        end
      end
    end
  end

  def index
    @users = User.all
    @book = Book.new
    @room = Room.new
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      flash[:notice] = @user.errors.full_messages
      render :edit
    end
  end
  
  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end
  
  def followeds
    @user = User.find(params[:id])
    @users = @user.followeds
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  def book_params
    params.require(:user).permit(:title, :body)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="5"></th>
    </tr>
  </thead>
  <tbody>
  
  
    <% users.each do |user| %>
      
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><span>フォロー数:</span><%= user.followeds.count %> </td>
        <td><span>フォロワー数:</span><%= user.followers.count %></td>
        
        <% if current_user != user %>
          <% if user.followed_by?(current_user) %>
            <td><%= link_to "フォロー外す", user_relationships_path(user), method: :delete %></td>
          <% else %>
            <td><%= link_to "フォローする", user_relationships_path(user), method: :post %></td>
          <% end %>
        <% end %>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
    
    
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followeds.count, followeds_user_path(user.id) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, followers_user_path(user.id) %></th>
  </tr>
</table>

<% unless user.id == current_user.id %>
  <% if @our_room == true %>
    <%= link_to "チャットを始める", room_path(@room_id) %>
  <% else %>
    <%= form_with model: @room do |f| %>
      <%= fields_for @user_room do |e| %>
        <%= e.hidden_field :user_id, value: @user.id %>
        <%= f.submit "チャットを始める" %>
      <% end %>
    <% end %>
  <% end %>  
<% end %></br>

<% if current_user != user %>
  <% if user.followed_by?(current_user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
  <% end %>  
<% end %>




<% if user.id == current_user.id %>
<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>
<% end %>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followed.html.erb
<h1>Follow Users</h1>
<% if @users.exists? %>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @users.each do |user| %>
      <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
      <td><%= user.followeds.name %></td>
      <td><span>フォロー数:</span><%= user.followeds.count %></td>
      <td><span>フォロワー数:</span><%= @user.followers.count %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      <% end %>
<% else %>
  <p>ユーザーはいません</p>
    </tr>
  </tbody>
</table>
<% end %>

app/views/users/followeds.html.erb
<h1>Follow Users</h1>


<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @users.each do |user| %>
      <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
      <td><%= user.name %></td>
      <td><span>フォロー数:</span><%= user.followeds.count %></td>
      <td><span>フォロワー数:</span><%= user.followers.count %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      </tr>
      <% end %>
<% unless @users.exists? %>
  <p>ユーザーはいません</p>
  <% end %>
  </tbody>
</table>

app/views/users/follower.html.erb
<h1>Follower Users</h1>
<% if @users.exists? %>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <% @users.each do |user| %>
          <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
          <td><%= user.name %></td>
          <td><span>フォロー数:</span><%= @user.followeds.count %></td>
          <td><span>フォロワー数:</span><%= user.count %></td>
          <td><%= link_to 'Show', user_path(user) %></td>
        <% end %>
<% else %>
  <p>ユーザーはいません</p>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/users/followers.html.erb
<h1>Follower Users</h1>
<% if @users.exists? %>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <% @users.each do |user| %>
          <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
          <td><%= user.name %></td>
          <td><span>フォロー数:</span><%= user.followeds.count %></td>
          <td><span>フォロワー数:</span><%= user.followers.count %></td>
          <td><%= link_to 'Show', user_path(user) %></td>
        <% end %>
        </tr>
<% else %>
  <p>ユーザーはいません</p>
    </tbody>
  </table>
<% end %>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
        <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
        <%= render 'books/form', book: @book %>
    </div>
<div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
        <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
        <%= render 'info', user: @user, book: @book %>
      <h2 class="mt-3">New book</h2>
        <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
        <%= render 'books/index',books: @user.books %>
    </div>
  </div>
</div>