config/routes.rb
Rails.application.routes.draw do
  get 'room/show'
  get 'room/create'
  get 'chats/create'
    devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  
  get 'search/search'
  root 'homes#top'
  get 'home/about' => "homes#about"
  

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :followers, on: :member
    get :followeds, on: :member
  end
  
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create, :destroy]
  end 
  
  resources :rooms, only: [:create, :show]
  resources :chats, only: [:create]
  
  resource :search, only: [:search]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites
	has_many :book_comments, dependent: :destroy

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
	
	def followed_by?(user)
    	active_relationships.find_by(followed_id: user.id).present?
	end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    
    belongs_to :user
    belongs_to :book
    
    validates :comment, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :followed, class_name: "User", optional: true
    belongs_to :follower, class_name: "User", optional: true
    
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :user_rooms, dependent: :destroy
    has_many :chats, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_many :active_relationships, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy
  has_many :followeds, through: :active_relationships, source: :follower
  
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :followed
  
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  
  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}
  validates :postal_code, presence: true
  validates :prefecture_code, presence: true
  validates :city, presence: true
  validates :street, presence: true
  
  def followed_by?(user)
    passive_relationships.find_by(followed_id: user.id).present?
  end
  
  def favorited_by?(user)
	 favorites.where(user_id: user.id).exists?
  end
  
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :ensure_correct_user, only: [:update,:edit]


  def show
   @book = Book.find(params[:id])
   @new_book = Book.new
  end

  def index
    @book = Book.new
    @books = Book.all
    @room = Room.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      flash[:notice] = @book.errors.full_messages
      render 'index'
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction)
  end
  
  def book_params
    params.require(:book).permit(:title, :body)    
  end
  
  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def create
    if UserRoom.where(user_id: current_user.id).present?
      @chat = Chat.create(params.require(:chat).permit(:user_id, :room_id, :content).merge(user_id: current_user.id))
    else
      flash[:alert] = "メッセージ送信に失敗しました。"
      redirect_to room_path(@chat.room_id)
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def show
    @room = Room.find(params[:id])
    if UserRoom.where(user_id: current_user.id, room_id: @room.id).present?
      @chats = @room.chats
      @chat = Chat.new
      @chat_user = @room.user_rooms
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def create
    @room = Room.create
    @my_user_room = UserRoom.create(user_id: current_user.id, room_id: @room.id)
    @your_user_room = UserRoom.create(params.require(:user_room).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to room_path(@room.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update,:edit]
  

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @room = Room.new
    @user_room = UserRoom.new
    @current_user_room = UserRoom.where(user_id: current_user.id)
    @your_user_room = UserRoom.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_user_room.each do |cu|
        @your_user_room.each do |u|
          if cu.room_id == u.room_id
            @our_room = true
            @room_id = cu.room_id
          else
            @room = Room.new
            @user_room = UserRoom.new
          end
        end
      end
    end
  end

  def index
    @users = User.all
    @book = Book.new
    @room = Room.new
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      flash[:notice] = @user.errors.full_messages
      render :edit
    end
  end
  
  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end
  
  def followeds
    @user = User.find(params[:id])
    @users = @user.followeds
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  def book_params
    params.require(:user).permit(:title, :body)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Book", class: 'btn btn-success' %>
  </div>
  <% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
      <th></th>
      <thzcolspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td class="favorite_btn_<%= book.id %>"><%= render "favorites/favorite", book: book %></td>
        <td><span>コメント数:</span><%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= @book.user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @book.user.introduction %></th>
  </tr>
   <tr>
    <th>follows</th>
    <th><%= link_to user.followeds.count, followeds_user_path(user.id) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, followers_user_path(user.id) %></th>
  </tr>
</table>

<% if current_user != user %>
  <% if user.followed_by?(current_user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
  <% end %>  
<% end %>

<% if user.id == current_user.id %>
<div class='row'>
  <%= link_to '',edit_user_path(@book.user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{@book.user.id}" %>
</div>
<% end %>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= form_with model:@book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Book", class: 'btn btn-success' %>
  </div>
<% end %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
        <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
        <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
        <%= render 'index', books: @books  %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      
      <h2>User info</h2>
        <%= render partial: 'info', locals: { user: @book.user } %>
      <h2 class="mt-3">New book</h2>
        <%= render 'form', book: @new_book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		  <table class='table'>
  		    <tr>
    		    <td>
    		      <%= link_to user_path(@book.user) do %>
              <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
              <%= @book.user.name %>
              <% end %>
            </td>
            <td><%= link_to @book.title, book_path(@book) %></td>
            <td><%= @book.body %></td>
            <td class="favorite_btn_<%= @book.id %>" >
              <%= render "favorites/favorite" , book: @book %>
            </td>
            <td id="comments_count">
              <span>コメント数:</span><%= @book.book_comments.count %>
            </td>

            <% if @book.user_id == current_user.id %>
              <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
              <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
            <% end %>
          </tr>
        </table>
      
        <div id="book_comments">
          <%= render "book_comments/index", book: @book, book_comments: @book.book_comments %>
        </div>
        <div id="book_comment_form">
          <%= render "book_comments/form", book: @book, book_comment: BookComment.new %>
        </div>
    </div>
  </div>
</div>

app/views/chats/create.js.erb
$('.chat').append("<div><%= @chat.content %></div>");
$('input[type=text]').val("")

app/views/chats/create.jsl.erb
$('.chat').append("<td><%= @chat.content %></td>");
$('input[type=text]').val("")

app/views/rooms/create.html.erb
<h1>Room#create</h1>
<p>Find me in app/views/room/create.html.erb</p>

app/views/rooms/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <% @chat_user.each do |chat_user| %>
        <% if chat_user.user.id != current_user.id %>
          <h1><%= chat_user.user.name %>さんとのチャット</h1>
        <% end %>
      <% end %>
      
      
      <div class="chat table">
        <% @chats.each do |chat| %>
          <% if chat.user_id == current_user.id %>
            <div style="text-align: left"><%= chat.content %></div>
          <% else %>
            <div style="text-align: right"><%= chat.content %></div>
          <% end %>
        <% end %>
      </div>

      <%= form_for @chat, remote: true do |f| %>
        <%= f.text_field :content %>
        <%= f.hidden_field :room_id, value: @room.id %>
        <% f.submit %>
      <% end %>
    </div>
  </div>
</div>